//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EtiquetaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EtiquetaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Etiqueta.EtiquetaResource", typeof(EtiquetaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string Abierto {
            get {
                return ResourceManager.GetString("Abierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Ampliar {
            get {
                return ResourceManager.GetString("Ampliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string Asginar {
            get {
                return ResourceManager.GetString("Asginar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention:.
        /// </summary>
        public static string Atencion {
            get {
                return ResourceManager.GetString("Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended.
        /// </summary>
        public static string Atendido {
            get {
                return ResourceManager.GetString("Atendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user&apos;s role ....
        /// </summary>
        public static string CargandoRoles {
            get {
                return ResourceManager.GetString("CargandoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string ConsultarRegistro {
            get {
                return ResourceManager.GetString("ConsultarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration mail sent.
        /// </summary>
        public static string CorreoRegistroEnviado {
            get {
                return ResourceManager.GetString("CorreoRegistroEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CrearRegistro {
            get {
                return ResourceManager.GetString("CrearRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded.
        /// </summary>
        public static string Descartado {
            get {
                return ResourceManager.GetString("Descartado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Detenido {
            get {
                return ResourceManager.GetString("Detenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditarRegistro {
            get {
                return ResourceManager.GetString("EditarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string EnMovimiento {
            get {
                return ResourceManager.GetString("EnMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending mail ....
        /// </summary>
        public static string EnviandoCorreo {
            get {
                return ResourceManager.GetString("EnviandoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string EstaSemana {
            get {
                return ResourceManager.GetString("EstaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string EsteMes {
            get {
                return ResourceManager.GetString("EsteMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string FueraDeLinea {
            get {
                return ResourceManager.GetString("FueraDeLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate excel.
        /// </summary>
        public static string GenerarExcel {
            get {
                return ResourceManager.GetString("GenerarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Hoy {
            get {
                return ResourceManager.GetString("Hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your query.
        /// </summary>
        public static string IngreseBusqueda {
            get {
                return ResourceManager.GetString("IngreseBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string MesPasado {
            get {
                return ResourceManager.GetString("MesPasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide filters.
        /// </summary>
        public static string MostrarOcultarFiltro {
            get {
                return ResourceManager.GetString("MostrarOcultarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string OlvideContrasena {
            get {
                return ResourceManager.GetString("OlvideContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active option.
        /// </summary>
        public static string OpcionActiva {
            get {
                return ResourceManager.GetString("OpcionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        public static string Procesando {
            get {
                return ResourceManager.GetString("Procesando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send registration mail.
        /// </summary>
        public static string ReenviarCorreoRegistro {
            get {
                return ResourceManager.GetString("ReenviarCorreoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string SemanaPasada {
            get {
                return ResourceManager.GetString("SemanaPasada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert notification is empty.
        /// </summary>
        public static string SinAlertasPendientes {
            get {
                return ResourceManager.GetString("SinAlertasPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        public static string Transferido {
            get {
                return ResourceManager.GetString("Transferido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string VolverAlLogin {
            get {
                return ResourceManager.GetString("VolverAlLogin", resourceCulture);
            }
        }
    }
}
