//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.MantenimientoInteligenteServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:moduloGCM", ConfigurationName="MantenimientoInteligenteServiceReference.moduloGCMPortType")]
    public interface moduloGCMPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:moduloGCM#sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool sendMessage(IntranetWeb.MantenimientoInteligenteServiceReference.requestGCM requestGCM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:moduloGCM#sendMessage", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> sendMessageAsync(IntranetWeb.MantenimientoInteligenteServiceReference.requestGCM requestGCM);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:moduloGCM")]
    public partial class requestGCM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string messageField;
        
        private string titleField;
        
        private int codeField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface moduloGCMPortTypeChannel : IntranetWeb.MantenimientoInteligenteServiceReference.moduloGCMPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class moduloGCMPortTypeClient : System.ServiceModel.ClientBase<IntranetWeb.MantenimientoInteligenteServiceReference.moduloGCMPortType>, IntranetWeb.MantenimientoInteligenteServiceReference.moduloGCMPortType {
        
        public moduloGCMPortTypeClient() {
        }
        
        public moduloGCMPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public moduloGCMPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public moduloGCMPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public moduloGCMPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool sendMessage(IntranetWeb.MantenimientoInteligenteServiceReference.requestGCM requestGCM) {
            return base.Channel.sendMessage(requestGCM);
        }
        
        public System.Threading.Tasks.Task<bool> sendMessageAsync(IntranetWeb.MantenimientoInteligenteServiceReference.requestGCM requestGCM) {
            return base.Channel.sendMessageAsync(requestGCM);
        }
    }
}
