//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CampoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CampoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Titulo.Campo.CampoResource", typeof(CampoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote opening supported.
        /// </summary>
        public static string AperturaRemota {
            get {
                return ResourceManager.GetString("AperturaRemota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunity / Street / House.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father position.
        /// </summary>
        public static string CargoPadre {
            get {
                return ResourceManager.GetString("CargoPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doument id.
        /// </summary>
        public static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client registred (mobile).
        /// </summary>
        public static string ClienteRegistradoMovil {
            get {
                return ResourceManager.GetString("ClienteRegistradoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance company.
        /// </summary>
        public static string CompaniaSeguro {
            get {
                return ResourceManager.GetString("CompaniaSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVR Password.
        /// </summary>
        public static string ContrasenaDVR {
            get {
                return ResourceManager.GetString("ContrasenaDVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Township.
        /// </summary>
        public static string Corregimiento {
            get {
                return ResourceManager.GetString("Corregimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position description.
        /// </summary>
        public static string DescripcionCargo {
            get {
                return ResourceManager.GetString("DescripcionCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Dispositivo {
            get {
                return ResourceManager.GetString("Dispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Distribuidor {
            get {
                return ResourceManager.GetString("Distribuidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform dealer.
        /// </summary>
        public static string DistribuidorPlataforma {
            get {
                return ResourceManager.GetString("DistribuidorPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Distrito {
            get {
                return ResourceManager.GetString("Distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Estatus {
            get {
                return ResourceManager.GetString("Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken date.
        /// </summary>
        public static string FechaApertura {
            get {
                return ResourceManager.GetString("FechaApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status date.
        /// </summary>
        public static string FechaEstatus {
            get {
                return ResourceManager.GetString("FechaEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification date.
        /// </summary>
        public static string FechaNotificacion {
            get {
                return ResourceManager.GetString("FechaNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record date.
        /// </summary>
        public static string FechaRegistro {
            get {
                return ResourceManager.GetString("FechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host GB.
        /// </summary>
        public static string GBHostSpot {
            get {
                return ResourceManager.GetString("GBHostSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification hour.
        /// </summary>
        public static string HoraNotificacion {
            get {
                return ResourceManager.GetString("HoraNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record hour.
        /// </summary>
        public static string HoraRegistro {
            get {
                return ResourceManager.GetString("HoraRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send sign in invitation.
        /// </summary>
        public static string IndicadorEnviarInvitacion {
            get {
                return ResourceManager.GetString("IndicadorEnviarInvitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active?.
        /// </summary>
        public static string IndicadorEstaActivo {
            get {
                return ResourceManager.GetString("IndicadorEstaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is registred?.
        /// </summary>
        public static string IndicadorEstaRegistrado {
            get {
                return ResourceManager.GetString("IndicadorEstaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial mileage.
        /// </summary>
        public static string KilometrajeInicial {
            get {
                return ResourceManager.GetString("KilometrajeInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total mileage.
        /// </summary>
        public static string KilometrajeTotal {
            get {
                return ResourceManager.GetString("KilometrajeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ListaRol {
            get {
                return ResourceManager.GetString("ListaRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile app services.
        /// </summary>
        public static string ListaServiciosApp {
            get {
                return ResourceManager.GetString("ListaServiciosApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS button location.
        /// </summary>
        public static string LocalizacionBotonSOS {
            get {
                return ResourceManager.GetString("LocalizacionBotonSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string NombreApellido {
            get {
                return ResourceManager.GetString("NombreApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string NombreAplicacion {
            get {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string NombreCargo {
            get {
                return ResourceManager.GetString("NombreCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string NombreDispositivo {
            get {
                return ResourceManager.GetString("NombreDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative unit.
        /// </summary>
        public static string NombreUnidadAdministrativa {
            get {
                return ResourceManager.GetString("NombreUnidadAdministrativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string NombreUsuarioCorreo {
            get {
                return ResourceManager.GetString("NombreUsuarioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your username or email.
        /// </summary>
        public static string NombreUsuarioLogin {
            get {
                return ResourceManager.GetString("NombreUsuarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis number.
        /// </summary>
        public static string NumeroChasis {
            get {
                return ResourceManager.GetString("NumeroChasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVR number.
        /// </summary>
        public static string NumeroDVR {
            get {
                return ResourceManager.GetString("NumeroDVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string NumeroMovil {
            get {
                return ResourceManager.GetString("NumeroMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string NumeroPlaca {
            get {
                return ResourceManager.GetString("NumeroPlaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string NumeroTelefonoFijo {
            get {
                return ResourceManager.GetString("NumeroTelefonoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office phone number.
        /// </summary>
        public static string NumeroTelefonoOficina {
            get {
                return ResourceManager.GetString("NumeroTelefonoOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person phone number.
        /// </summary>
        public static string NumeroTelefonoPersonaContacto {
            get {
                return ResourceManager.GetString("NumeroTelefonoPersonaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number.
        /// </summary>
        public static string NumeroTicket {
            get {
                return ResourceManager.GetString("NumeroTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person name.
        /// </summary>
        public static string PersonaContacto {
            get {
                return ResourceManager.GetString("PersonaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        public static string RepetirContrasena {
            get {
                return ResourceManager.GetString("RepetirContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business segment.
        /// </summary>
        public static string SegmentoNegocio {
            get {
                return ResourceManager.GetString("SegmentoNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sims.
        /// </summary>
        public static string Sims {
            get {
                return ResourceManager.GetString("Sims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business partner.
        /// </summary>
        public static string SocioComercial {
            get {
                return ResourceManager.GetString("SocioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim card.
        /// </summary>
        public static string TarjetaSim {
            get {
                return ResourceManager.GetString("TarjetaSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote off type.
        /// </summary>
        public static string TipoApagadoRemoto {
            get {
                return ResourceManager.GetString("TipoApagadoRemoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case type.
        /// </summary>
        public static string TipoCaso {
            get {
                return ResourceManager.GetString("TipoCaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close type.
        /// </summary>
        public static string TipoCierre {
            get {
                return ResourceManager.GetString("TipoCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type.
        /// </summary>
        public static string TipoCombustible {
            get {
                return ResourceManager.GetString("TipoCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type.
        /// </summary>
        public static string TipoNotificacion {
            get {
                return ResourceManager.GetString("TipoNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood type.
        /// </summary>
        public static string TipoSangre {
            get {
                return ResourceManager.GetString("TipoSangre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission type.
        /// </summary>
        public static string TipoTransmision {
            get {
                return ResourceManager.GetString("TipoTransmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User alert.
        /// </summary>
        public static string UsuarioAlerta {
            get {
                return ResourceManager.GetString("UsuarioAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ticket.
        /// </summary>
        public static string UsuarioTicket {
            get {
                return ResourceManager.GetString("UsuarioTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehiculo {
            get {
                return ResourceManager.GetString("Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance policy validity.
        /// </summary>
        public static string VigenciaPoliza {
            get {
                return ResourceManager.GetString("VigenciaPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string Vin {
            get {
                return ResourceManager.GetString("Vin", resourceCulture);
            }
        }
    }
}
