//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Error.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position doesn&apos;t exists.
        /// </summary>
        public static string CargoNoExiste {
            get {
                return ResourceManager.GetString("CargoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position&apos;s father can not be updated because there is personnel with this position: {0}.
        /// </summary>
        public static string CargoPadreNoActualizable {
            get {
                return ResourceManager.GetString("CargoPadreNoActualizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position&apos;s father can not be updated bucause exists more than one posible new supervisor than can be reasigne to the employees on this position.
        /// </summary>
        public static string CargoPadreNoActualizableReasignarSupervisor {
            get {
                return ResourceManager.GetString("CargoPadreNoActualizableReasignarSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not valid or user is inactive. Please verify.
        /// </summary>
        public static string ContrasenaInvalida {
            get {
                return ResourceManager.GetString("ContrasenaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords doesn&apos;t match. Please verify.
        /// </summary>
        public static string ContrasenaNoCoincide {
            get {
                return ResourceManager.GetString("ContrasenaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create Controller Context if no active HttpContext instance is available.
        /// </summary>
        public static string ControllerContextNoCreable {
            get {
                return ResourceManager.GetString("ControllerContextNoCreable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration mail couldn&apos;t be send.
        /// </summary>
        public static string CorreoRegistroNoEnviado {
            get {
                return ResourceManager.GetString("CorreoRegistroNoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already used.
        /// </summary>
        public static string CorreoUsuarioExistente {
            get {
                return ResourceManager.GetString("CorreoUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing request. (100).
        /// </summary>
        public static string Error100 {
            get {
                return ResourceManager.GetString("Error100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating profile. Contact sytem administrator.
        /// </summary>
        public static string FalloActulizarPerfil {
            get {
                return ResourceManager.GetString("FalloActulizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be send.
        /// </summary>
        public static string FalloEnvioContrasena {
            get {
                return ResourceManager.GetString("FalloEnvioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s must be between 6 and 20 characters long, must contain al least one digit, an alphanumeric character and a special character (@#$%*).
        /// </summary>
        public static string FormatoContrasenaInvalida {
            get {
                return ResourceManager.GetString("FormatoContrasenaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string FormatoEmailInvalido {
            get {
                return ResourceManager.GetString("FormatoEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday has an invalid format.
        /// </summary>
        public static string FormatoFechaNacimientoInvalido {
            get {
                return ResourceManager.GetString("FormatoFechaNacimientoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must not have spaces, only the special characters &quot;.&quot; and &quot;_&quot; are admitted and a length between 5 and 50.
        /// </summary>
        public static string FormatoNombreUsuarioInvalido {
            get {
                return ResourceManager.GetString("FormatoNombreUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a valid phone number.
        /// </summary>
        public static string FormatoTenefonoFijoInvalido {
            get {
                return ResourceManager.GetString("FormatoTenefonoFijoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already used.
        /// </summary>
        public static string NombreUsuarioExistente {
            get {
                return ResourceManager.GetString("NombreUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not valid.
        /// </summary>
        public static string NombreUsuarioInvalido {
            get {
                return ResourceManager.GetString("NombreUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another client with the same document id.
        /// </summary>
        public static string NumeroDeDocumentoClienteEnUso {
            get {
                return ResourceManager.GetString("NumeroDeDocumentoClienteEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another employee with the same document id.
        /// </summary>
        public static string NumeroDeDocumentoEmpleadoEnUso {
            get {
                return ResourceManager.GetString("NumeroDeDocumentoEmpleadoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another user with the same document number.
        /// </summary>
        public static string NumeroDeDocumentoEnUso {
            get {
                return ResourceManager.GetString("NumeroDeDocumentoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another provider with the same document id.
        /// </summary>
        public static string NumeroDeDocumentoProveedorEnUso {
            get {
                return ResourceManager.GetString("NumeroDeDocumentoProveedorEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another business partner with the same document id.
        /// </summary>
        public static string NumeroDeDocumentoSocioComercialEnUso {
            get {
                return ResourceManager.GetString("NumeroDeDocumentoSocioComercialEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID is not valid.
        /// </summary>
        public static string NumeroDocumentoInvalido {
            get {
                return ResourceManager.GetString("NumeroDocumentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has foreing key with another table. (Relation &quot;{0}&quot;).
        /// </summary>
        public static string RegistroConFK {
            get {
                return ResourceManager.GetString("RegistroConFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record couln&apos;t be updated- Try again later.
        /// </summary>
        public static string RegistroNoActualizado {
            get {
                return ResourceManager.GetString("RegistroNoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record couldn&apos;t be deleted. Try again later please.
        /// </summary>
        public static string RegistroNoEliminado {
            get {
                return ResourceManager.GetString("RegistroNoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor is required.
        /// </summary>
        public static string SupervisorObligatorio {
            get {
                return ResourceManager.GetString("SupervisorObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not valid.
        /// </summary>
        public static string TelefonoFijoInvalido {
            get {
                return ResourceManager.GetString("TelefonoFijoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a valid mobile number.
        /// </summary>
        public static string TelefonoMovilInvalido {
            get {
                return ResourceManager.GetString("TelefonoMovilInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can not be inactive because it have the following personnel in charge: {0}.
        /// </summary>
        public static string UsuarioActivoNoActualizable {
            get {
                return ResourceManager.GetString("UsuarioActivoNoActualizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User invalid or inactive.
        /// </summary>
        public static string UsuarioInvalidoInactivo {
            get {
                return ResourceManager.GetString("UsuarioInvalidoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s position can not be updated because it has personnel under his charge. Please reassign the following employees supervisor: {0}.
        /// </summary>
        public static string UsuarioNuevoCargoNoActualizable {
            get {
                return ResourceManager.GetString("UsuarioNuevoCargoNoActualizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vin number belongs to another vehicle.
        /// </summary>
        public static string VinEnUso {
            get {
                return ResourceManager.GetString("VinEnUso", resourceCulture);
            }
        }
    }
}
