//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeCorreoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeCorreoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Correo.Mensaje.MensajeCorreoResource", typeof(MensajeCorreoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested a password change. &lt;br/&gt;&lt;br/&gt; Your new password is: &lt;strong&gt; {0} &lt;/strong&gt; .
        /// </summary>
        public static string CambioContrasena {
            get {
                return ResourceManager.GetString("CambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string RecuperarContrasena {
            get {
                return ResourceManager.GetString("RecuperarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear (a) {0} &lt;br/&gt; We want to give you a cordial welcome as a customer of Sai Innovación.&lt;br/&gt; From now on you and your vehicle become part of our family, we are pleased to offer our services and remind you always be happy to assist you want. With a team of highly trained professionals and advanced technology guarantee quality service to improve your driving experience. &lt;br/&gt; The following are the registration data of your account : &lt;br/&gt; User: &lt;strong&gt; {1} &lt;/ strong&gt; &lt;br/&gt; Password: &lt;strong&gt; {2} &lt;/ strong&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Registro {
            get {
                return ResourceManager.GetString("Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to give you a cordial welcome as an employee on Sai Innovación&apos;s platform. &lt;br/&gt; The following are the registration data of your account: &lt;br/&gt; User: &lt;strong&gt; {0} &lt;/ strong&gt; &lt;br/&gt; Password: &lt;strong&gt; {1} &lt;/ strong&gt;&lt;br/&gt;.
        /// </summary>
        public static string RegistroEmpleado {
            get {
                return ResourceManager.GetString("RegistroEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to give you a cordial welcome as a business partner of Sai Innovación. &lt;br/&gt; We are pleased to offer our services. &lt;br/&gt; The following are the registration data of your account: &lt;br/&gt; User: &lt;strong&gt; {0} &lt;/ strong&gt; &lt;br/&gt; Password: &lt;strong&gt; {1} &lt;/ strong&gt; &lt;br/&gt;.
        /// </summary>
        public static string RegistroSocio {
            get {
                return ResourceManager.GetString("RegistroSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to give you a cordial welcome as an user on {0} on Sai Innovación&apos;s platform. &lt;br/&gt; We are pleased to offer our services. &lt;br/&gt; The following are the registration data of your account: &lt;br/&gt; User: &lt;strong&gt; {1} &lt;/ strong&gt; &lt;br/&gt; Password: &lt;strong&gt; {2} &lt;/ strong&gt;&lt;br/&gt;.
        /// </summary>
        public static string RegistroUsuarioInterno {
            get {
                return ResourceManager.GetString("RegistroUsuarioInterno", resourceCulture);
            }
        }
    }
}
