//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExitoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExitoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Exito.ExitoResource", typeof(ExitoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string CambioContrasena {
            get {
                return ResourceManager.GetString("CambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string CargoActualizado {
            get {
                return ResourceManager.GetString("CargoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string CargoCreado {
            get {
                return ResourceManager.GetString("CargoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position &lt;b&gt;{0}&lt;/b&gt; deleted successfully.
        /// </summary>
        public static string CargoEliminado {
            get {
                return ResourceManager.GetString("CargoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string ClienteCreado {
            get {
                return ResourceManager.GetString("ClienteCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password have been sent to your email address.
        /// </summary>
        public static string ContrasenaEnviada {
            get {
                return ResourceManager.GetString("ContrasenaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration mail sent successfully.
        /// </summary>
        public static string CorreoRegistroEnviado {
            get {
                return ResourceManager.GetString("CorreoRegistroEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device &lt;b&gt;{0}&lt;/b&gt; linked successfully.
        /// </summary>
        public static string DispositivoVinculado {
            get {
                return ResourceManager.GetString("DispositivoVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string EmpleadoActualizado {
            get {
                return ResourceManager.GetString("EmpleadoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string EmpleadoCreado {
            get {
                return ResourceManager.GetString("EmpleadoCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert deleted successfully.
        /// </summary>
        public static string NotificacionEliminada {
            get {
                return ResourceManager.GetString("NotificacionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        public static string PerfilActualizado {
            get {
                return ResourceManager.GetString("PerfilActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string ProveedorActualizado {
            get {
                return ResourceManager.GetString("ProveedorActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string ProveedorCreado {
            get {
                return ResourceManager.GetString("ProveedorCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string RolActualizado {
            get {
                return ResourceManager.GetString("RolActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &lt;b&gt;{0}&lt;/b&gt; created successfully .
        /// </summary>
        public static string RolCreado {
            get {
                return ResourceManager.GetString("RolCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business partner &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string SocioComercialActualizado {
            get {
                return ResourceManager.GetString("SocioComercialActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business partner &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string SocioComercialCreado {
            get {
                return ResourceManager.GetString("SocioComercialCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &lt;b&gt;{0}&lt;/b&gt; updated successfully.
        /// </summary>
        public static string UsuarioActualizado {
            get {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string UsuarioCreado {
            get {
                return ResourceManager.GetString("UsuarioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &lt;b&gt;{0}&lt;/b&gt; deleted successfully.
        /// </summary>
        public static string UsuarioEliminado {
            get {
                return ResourceManager.GetString("UsuarioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle &lt;b&gt;{0}&lt;/b&gt; created successfully.
        /// </summary>
        public static string VehiculoCreado {
            get {
                return ResourceManager.GetString("VehiculoCreado", resourceCulture);
            }
        }
    }
}
