//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TituloPaginaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TituloPaginaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Titulo.Pagina.TituloPaginaResource", typeof(TituloPaginaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent alerts.
        /// </summary>
        public static string AlertasAgentes {
            get {
                return ResourceManager.GetString("AlertasAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociate device.
        /// </summary>
        public static string AsociarDispositivo {
            get {
                return ResourceManager.GetString("AsociarDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociate vehicle.
        /// </summary>
        public static string AsociarVehiculo {
            get {
                return ResourceManager.GetString("AsociarVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Cargo {
            get {
                return ResourceManager.GetString("Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check employee.
        /// </summary>
        public static string ConsultarEmpleado {
            get {
                return ResourceManager.GetString("ConsultarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check notification.
        /// </summary>
        public static string ConsultarNotificacion {
            get {
                return ResourceManager.GetString("ConsultarNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check provider.
        /// </summary>
        public static string ConsultarProveedor {
            get {
                return ResourceManager.GetString("ConsultarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check business partner.
        /// </summary>
        public static string ConsultarSocioComercial {
            get {
                return ResourceManager.GetString("ConsultarSocioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ticket.
        /// </summary>
        public static string ConsultarTicket {
            get {
                return ResourceManager.GetString("ConsultarTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check user.
        /// </summary>
        public static string ConsultarUsuario {
            get {
                return ResourceManager.GetString("ConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create position.
        /// </summary>
        public static string CrearCargo {
            get {
                return ResourceManager.GetString("CrearCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string CrearCliente {
            get {
                return ResourceManager.GetString("CrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create provider.
        /// </summary>
        public static string CrearProveedor {
            get {
                return ResourceManager.GetString("CrearProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create GCM operator answer.
        /// </summary>
        public static string CrearRespuestaOperadorGCM {
            get {
                return ResourceManager.GetString("CrearRespuestaOperadorGCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string CrearRol {
            get {
                return ResourceManager.GetString("CrearRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create business partner.
        /// </summary>
        public static string CrearSocioComercial {
            get {
                return ResourceManager.GetString("CrearSocioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate employee relationship.
        /// </summary>
        public static string DarBajaEmpleado {
            get {
                return ResourceManager.GetString("DarBajaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string DatosAdicionales {
            get {
                return ResourceManager.GetString("DatosAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit position.
        /// </summary>
        public static string EditarCargo {
            get {
                return ResourceManager.GetString("EditarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string EditarEmpleado {
            get {
                return ResourceManager.GetString("EditarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit provider.
        /// </summary>
        public static string EditarProveedor {
            get {
                return ResourceManager.GetString("EditarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string EditarRol {
            get {
                return ResourceManager.GetString("EditarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit business partner.
        /// </summary>
        public static string EditarSocioComercial {
            get {
                return ResourceManager.GetString("EditarSocioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditarUsuario {
            get {
                return ResourceManager.GetString("EditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Localizacion {
            get {
                return ResourceManager.GetString("Localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string MonitorAlerta {
            get {
                return ResourceManager.GetString("MonitorAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor&apos;s administrator.
        /// </summary>
        public static string MonitorAlertaAdmin {
            get {
                return ResourceManager.GetString("MonitorAlertaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de usuario.
        /// </summary>
        public static string PerfilUsuario {
            get {
                return ResourceManager.GetString("PerfilUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Proveedor {
            get {
                return ResourceManager.GetString("Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert report.
        /// </summary>
        public static string ReporteAlertas {
            get {
                return ResourceManager.GetString("ReporteAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets report.
        /// </summary>
        public static string ReporteTickets {
            get {
                return ResourceManager.GetString("ReporteTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business partner.
        /// </summary>
        public static string SocioComercial {
            get {
                return ResourceManager.GetString("SocioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User (Admin).
        /// </summary>
        public static string UsuarioAdmin {
            get {
                return ResourceManager.GetString("UsuarioAdmin", resourceCulture);
            }
        }
    }
}
