//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdvertenciaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdvertenciaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntranetWeb.LocalizationResources.Advertencia.AdvertenciaResource", typeof(AdvertenciaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no charges to show.
        /// </summary>
        public static string CargosVacio {
            get {
                return ResourceManager.GetString("CargosVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close tab?.
        /// </summary>
        public static string ConfirmarCerrarTab {
            get {
                return ResourceManager.GetString("ConfirmarCerrarTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to disable permantly the employee? .
        /// </summary>
        public static string ConfirmarDarBaja {
            get {
                return ResourceManager.GetString("ConfirmarDarBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to logout?.
        /// </summary>
        public static string ConfirmarDesloguear {
            get {
                return ResourceManager.GetString("ConfirmarDesloguear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to delete the position?.
        /// </summary>
        public static string ConfirmarEliminarCargo {
            get {
                return ResourceManager.GetString("ConfirmarEliminarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to delete the user?.
        /// </summary>
        public static string ConfirmarEliminarUsuario {
            get {
                return ResourceManager.GetString("ConfirmarEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to delete the alert?.
        /// </summary>
        public static string EliminarNotificacion {
            get {
                return ResourceManager.GetString("EliminarNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send record information to the user?.
        /// </summary>
        public static string EnviarCorreoRegistro {
            get {
                return ResourceManager.GetString("EnviarCorreoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s menu is empty.
        /// </summary>
        public static string MenuAplicacionesVacio {
            get {
                return ResourceManager.GetString("MenuAplicacionesVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert has been taken by other user.
        /// </summary>
        public static string NotificacionGestionada {
            get {
                return ResourceManager.GetString("NotificacionGestionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no result for this query.
        /// </summary>
        public static string SinResultado {
            get {
                return ResourceManager.GetString("SinResultado", resourceCulture);
            }
        }
    }
}
