//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APLICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APLICACION()
        {
            this.APLICACION1 = new HashSet<APLICACION>();
            this.USUARIO_APLICACION = new HashSet<USUARIO_APLICACION>();
            this.ROL = new HashSet<ROL>();
            this.MENU_SERVICIO = new HashSet<MENU_SERVICIO>();
        }
    
        public int CD_APLICACION { get; set; }
        public string NM_APLICACION { get; set; }
        public string DE_APLICACION { get; set; }
        public string NM_CONTROLADOR { get; set; }
        public string NM_ACCION { get; set; }
        public string DE_PARAMETROS { get; set; }
        public string DE_ALIAS { get; set; }
        public Nullable<int> CD_APLICACION_PADRE { get; set; }
        public bool IN_APLICACION_INACTIVA { get; set; }
        public bool IN_ASIGNABLE { get; set; }
        public string NM_ICONO_MENU { get; set; }
        public string NM_ICONO_ACCESO_RAPIDO { get; set; }
        public bool IN_ES_DASHBOARD { get; set; }
        public bool IN_ES_PERFIL_USUARIO { get; set; }
        public int NU_ORDEN { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APLICACION> APLICACION1 { get; set; }
        public virtual APLICACION APLICACION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_APLICACION> USUARIO_APLICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROL> ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_SERVICIO> MENU_SERVICIO { get; set; }
    }
}
