//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
            this.NOTIFICACION_SIN_GESTION = new HashSet<NOTIFICACION_SIN_GESTION>();
            this.TICKET = new HashSet<TICKET>();
            this.DISPOSITIVO_CLIENTE = new HashSet<DISPOSITIVO_CLIENTE>();
            this.SOLICITUD_MANTENIMIENTO = new HashSet<SOLICITUD_MANTENIMIENTO>();
        }
    
        public int CD_CLIENTE { get; set; }
        public string DE_NOMBRE { get; set; }
        public string DE_APELLIDO { get; set; }
        public string DE_NOMBRE_APELLIDO_RAZON_SOCIAL { get; set; }
        public Nullable<System.DateTime> FE_NACIMIENTO { get; set; }
        public Nullable<int> CD_PAIS { get; set; }
        public Nullable<int> CD_PROVINCIA { get; set; }
        public Nullable<int> CD_DISTRITO { get; set; }
        public Nullable<int> CD_CORREGIMIENTO { get; set; }
        public string DI_COBRO { get; set; }
        public Nullable<int> NU_TELEFONO_OFICINA { get; set; }
        public string TP_SANGRE { get; set; }
        public string NM_PERSONA_CONTACTO { get; set; }
        public Nullable<int> NU_TELEFONO_MOVIL_PERSONA_CONTACTO { get; set; }
        public Nullable<int> CD_COMPANIA_SEGURO { get; set; }
        public bool IN_INACTIVO { get; set; }
        public Nullable<System.DateTime> FE_INACTIVO { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
        public System.DateTime FE_CREACION { get; set; }
    
        public virtual COMPANIA_SEGURO COMPANIA_SEGURO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_SIN_GESTION> NOTIFICACION_SIN_GESTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
        public virtual CORREGIMIENTO CORREGIMIENTO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual TIPO_SANGRE TIPO_SANGRE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPOSITIVO_CLIENTE> DISPOSITIVO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_MANTENIMIENTO> SOLICITUD_MANTENIMIENTO { get; set; }
    }
}
