//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION_KILOMETRAJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFIGURACION_KILOMETRAJE()
        {
            this.SOLICITUD_MANTENIMIENTO = new HashSet<SOLICITUD_MANTENIMIENTO>();
            this.OPERACION_MANTENIMIENTO = new HashSet<OPERACION_MANTENIMIENTO>();
        }
    
        public int CD_CONFIGURACION_KILOMETRAJE { get; set; }
        public int CD_TALLER { get; set; }
        public int CD_ANO { get; set; }
        public int CD_MODELO { get; set; }
        public int MT_KILOMETRAJE { get; set; }
    
        public virtual ANO_VEHICULO ANO_VEHICULO { get; set; }
        public virtual TALLER TALLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_MANTENIMIENTO> SOLICITUD_MANTENIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERACION_MANTENIMIENTO> OPERACION_MANTENIMIENTO { get; set; }
    }
}
