//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOSITIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISPOSITIVO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID_DISPOSITIVO { get; set; }
        public int ID_DISTRIBUIDOR { get; set; }
        public string NM_DISPOSITIVO { get; set; }
        public string DE_DISPOSITIVO { get; set; }
        public string NU_SERIAL { get; set; }
        public string NU_DVR { get; set; }
        public string NU_SIM_GPS { get; set; }
        public Nullable<int> CD_MODELO { get; set; }
        public bool IN_ELIMINADO { get; set; }
    
        public virtual DISPOSITIVO_CLIENTE DISPOSITIVO_CLIENTE { get; set; }
        public virtual DISTRIBUIDOR DISTRIBUIDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
