//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUIDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRIBUIDOR()
        {
            this.SOCIO_COMERCIAL = new HashSet<SOCIO_COMERCIAL>();
            this.DISPOSITIVO = new HashSet<DISPOSITIVO>();
        }
    
        public int ID_DISTRIBUIDOR { get; set; }
        public string NM_DISTRIBUIDOR { get; set; }
        public string NM_USUARIO { get; set; }
        public string DE_CONTRASENA { get; set; }
        public bool IN_ELIMINADO { get; set; }
        public Nullable<int> ID_DISTRIBUIDOR_PADRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIO_COMERCIAL> SOCIO_COMERCIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPOSITIVO> DISPOSITIVO { get; set; }
    }
}
