//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KILOMETRAJE_TOTAL
    {
        public int UserID { get; set; }
        public int DeviceID { get; set; }
        public double MontoKilometrajeInicial { get; set; }
        public double MontoKilometrajeDispositivo { get; set; }
        public double MontoKilometrajeTotal { get; set; }
    }
}
