//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU_SERVICIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
            this.SEGMENTO_NEGOCIO = new HashSet<SEGMENTO_NEGOCIO>();
        }
    
        public int CD_MENU_SERVICIO { get; set; }
        public string NM_SERVICIO { get; set; }
        public string DE_SERVICIO { get; set; }
        public Nullable<int> CD_APLICACION { get; set; }
        public bool IN_INACTIVO { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
    
        public virtual APLICACION APLICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGMENTO_NEGOCIO> SEGMENTO_NEGOCIO { get; set; }
    }
}
