//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION_MANTENIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERACION_MANTENIMIENTO()
        {
            this.CONFIGURACION_KILOMETRAJE = new HashSet<CONFIGURACION_KILOMETRAJE>();
        }
    
        public int CD_OPERACION { get; set; }
        public string DE_ALIAS_OPERACION { get; set; }
        public int CD_TALLER { get; set; }
        public string NM_OPERACION_MANTENIMIENTO { get; set; }
        public int MT_MINUTO_DURACION_OPERACION { get; set; }
    
        public virtual TALLER TALLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFIGURACION_KILOMETRAJE> CONFIGURACION_KILOMETRAJE { get; set; }
    }
}
