//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA_CORREO
    {
        public int CD_PLANTILLA_CORREO { get; set; }
        public string NM_PLANTILLA_CORREO { get; set; }
        public int TP_PLANTILLA_CORREO { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public string DE_TITULO_CORREO { get; set; }
        public string DE_CONTENIDO_PLANTILLA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPO_PLANTILLA_CORREO TIPO_PLANTILLA_CORREO { get; set; }
    }
}
