//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAI_notificationLocationImage
    {
        public int id { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> BaiduLat { get; set; }
        public Nullable<double> BaiduLng { get; set; }
        public Nullable<double> OLat { get; set; }
        public Nullable<double> OLng { get; set; }
        public string locationAddress { get; set; }
        public string imageName { get; set; }
        public byte[] imageContent { get; set; }
    }
}
