//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_MANTENIMIENTO
    {
        public int CD_SOLICITUD { get; set; }
        public int CD_TALLER { get; set; }
        public int CD_CONFIGURACION_KILOMETRAJE { get; set; }
        public int CD_USUARIO_SOLICITANTE { get; set; }
        public int CD_CLIENTE { get; set; }
        public System.DateTime FE_SOLICITUD { get; set; }
        public string DE_ESTATUS_SOLICITUD { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
        public int CD_VEHICULO { get; set; }
        public Nullable<int> ID_DISPOSITIVO { get; set; }
        public string DE_OBSERVACION { get; set; }
    
        public virtual DISPOSITIVO_CLIENTE DISPOSITIVO_CLIENTE { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        public virtual CONFIGURACION_KILOMETRAJE CONFIGURACION_KILOMETRAJE { get; set; }
        public virtual TALLER TALLER { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
