//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TALLER()
        {
            this.CONFIGURACION_KILOMETRAJE = new HashSet<CONFIGURACION_KILOMETRAJE>();
            this.OPERACION_MANTENIMIENTO = new HashSet<OPERACION_MANTENIMIENTO>();
            this.SOLICITUD_MANTENIMIENTO = new HashSet<SOLICITUD_MANTENIMIENTO>();
        }
    
        public int CD_TALLER { get; set; }
        public string NM_TALLER { get; set; }
        public int CD_PAIS { get; set; }
        public int CD_PROVINCIA { get; set; }
        public int CD_DISTRITO { get; set; }
        public Nullable<int> CD_CORREGIMIENTO { get; set; }
        public string DI_TALLER { get; set; }
        public Nullable<int> CD_SOCIO_COMERCIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFIGURACION_KILOMETRAJE> CONFIGURACION_KILOMETRAJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERACION_MANTENIMIENTO> OPERACION_MANTENIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_MANTENIMIENTO> SOLICITUD_MANTENIMIENTO { get; set; }
        public virtual CORREGIMIENTO CORREGIMIENTO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual SOCIO_COMERCIAL SOCIO_COMERCIAL { get; set; }
    }
}
