//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_HISTORICO
    {
        public int ID_TICKET_HISTORICO { get; set; }
        public int ID_TICKET { get; set; }
        public int ID_NOTIFICACION { get; set; }
        public int ID_ORIGEN_NOTIFICACION { get; set; }
        public int TP_NOTIFICACION { get; set; }
        public Nullable<int> TP_ATENCION { get; set; }
        public int ID_DISTRIBUIDOR { get; set; }
        public int ID_DISPOSITIVO { get; set; }
        public string ID_USUARIO_MOVIL { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
        public int ID_ESTATUS_TICKET { get; set; }
        public Nullable<int> ID_RESPUESTA_OPERADOR { get; set; }
        public bool IN_RESPUESTA_ENVIADA { get; set; }
        public string DE_OBSERVACION { get; set; }
        public string DE_OBSERVACION_SUPERVISOR { get; set; }
        public int CD_USUARIO { get; set; }
        public Nullable<int> CD_USUARIO_TRANSFERENCIA { get; set; }
        public System.DateTime FE_NOTIFICACION { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
    }
}
