//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_MOVIL_GCM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO_MOVIL_GCM()
        {
            this.NOTIFICACION_GCM = new HashSet<NOTIFICACION_GCM>();
        }
    
        public int CD_USUARIO_GCM { get; set; }
        public int CD_USUARIO { get; set; }
        public string ID_GCM { get; set; }
        public string NM_SO_VERSION { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
        public bool IN_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_GCM> NOTIFICACION_GCM { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
