//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.USUARIO_NOTIFICACION = new HashSet<USUARIO_NOTIFICACION>();
            this.NOTIFICACION_SIN_GESTION = new HashSet<NOTIFICACION_SIN_GESTION>();
            this.TICKET = new HashSet<TICKET>();
            this.TICKET1 = new HashSet<TICKET>();
            this.LOG_TRANSACCIONES = new HashSet<LOG_TRANSACCIONES>();
            this.USUARIO_APLICACION = new HashSet<USUARIO_APLICACION>();
            this.USUARIO_MOVIL_GCM = new HashSet<USUARIO_MOVIL_GCM>();
            this.ROL = new HashSet<ROL>();
            this.USUARIO1 = new HashSet<USUARIO>();
            this.USUARIO2 = new HashSet<USUARIO>();
            this.DISPOSITIVO = new HashSet<DISPOSITIVO>();
            this.MENU_SERVICIO = new HashSet<MENU_SERVICIO>();
            this.PLANTILLA_CORREO = new HashSet<PLANTILLA_CORREO>();
            this.SOLICITUD_MANTENIMIENTO = new HashSet<SOLICITUD_MANTENIMIENTO>();
        }
    
        public int CD_USUARIO { get; set; }
        public string NM_USUARIO { get; set; }
        public string TP_DOCUMENTO_IDENTIDAD { get; set; }
        public string NU_DOCUMENTO_IDENTIDAD { get; set; }
        public string DE_NOMBRE_APELLIDO { get; set; }
        public byte[] DE_CONTRASENA { get; set; }
        public Nullable<System.DateTime> FE_NACIMIENTO { get; set; }
        public string DI_EMAIL_USUARIO { get; set; }
        public Nullable<int> NU_TELEFONO_FIJO { get; set; }
        public Nullable<int> NU_TELEFONO_MOVIL { get; set; }
        public bool IN_REGISTRO_MOVIL { get; set; }
        public Nullable<System.DateTime> FE_REGISTRO_MOVIL { get; set; }
        public bool IN_USUARIO_INACTIVO { get; set; }
        public bool IN_USUARIO_BLOQUEADO { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
        public bool IN_CORREO_REGISTRO_ENVIADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_NOTIFICACION> USUARIO_NOTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION_SIN_GESTION> NOTIFICACION_SIN_GESTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET1 { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual SOCIO_COMERCIAL SOCIO_COMERCIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_TRANSACCIONES> LOG_TRANSACCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_APLICACION> USUARIO_APLICACION { get; set; }
        public virtual TIPO_DOCUMENTO_IDENTIDAD TIPO_DOCUMENTO_IDENTIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_MOVIL_GCM> USUARIO_MOVIL_GCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROL> ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPOSITIVO> DISPOSITIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_SERVICIO> MENU_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTILLA_CORREO> PLANTILLA_CORREO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_MANTENIMIENTO> SOLICITUD_MANTENIMIENTO { get; set; }
    }
}
