//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_NOTIFICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO_NOTIFICACION()
        {
            this.IMAGEN_NOTIFICACION = new HashSet<IMAGEN_NOTIFICACION>();
        }
    
        public int ID_NOTFICACION { get; set; }
        public int ID_ORIGEN_NOTIFICACION { get; set; }
        public int CD_USUARIO { get; set; }
        public Nullable<int> ID_DISPOSITIVO { get; set; }
        public int TP_NOTIFICACION { get; set; }
        public System.DateTime FE_CREACION { get; set; }
        public System.DateTime FE_ESTATUS { get; set; }
        public bool IN_GESTIONADA { get; set; }
    
        public virtual TIPO_NOTIFICACION TIPO_NOTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN_NOTIFICACION> IMAGEN_NOTIFICACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual DISPOSITIVO_CLIENTE DISPOSITIVO_CLIENTE { get; set; }
    }
}
