//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.DISPOSITIVO_CLIENTE = new HashSet<DISPOSITIVO_CLIENTE>();
            this.SOLICITUD_MANTENIMIENTO = new HashSet<SOLICITUD_MANTENIMIENTO>();
        }
    
        public int CD_VEHICULO { get; set; }
        public int CD_CLIENTE { get; set; }
        public string NU_VIN { get; set; }
        public string NU_PLACA { get; set; }
        public Nullable<int> CD_MARCA { get; set; }
        public Nullable<int> CD_MODELO { get; set; }
        public string NM_COLOR { get; set; }
        public Nullable<int> CD_ANO { get; set; }
        public Nullable<int> TP_COMBUSTIBLE { get; set; }
        public Nullable<int> TP_CIERRE_VEHICULO { get; set; }
        public Nullable<int> TP_TRANSMISION_VEHICULO { get; set; }
        public Nullable<int> CD_COMPANIA_SEGURO { get; set; }
        public Nullable<System.DateTime> FE_SEGURO_VIGENCIA_HASTA { get; set; }
    
        public virtual ANO_VEHICULO ANO_VEHICULO { get; set; }
        public virtual COMPANIA_SEGURO COMPANIA_SEGURO { get; set; }
        public virtual TIPO_CIERRE_VEHICULO TIPO_CIERRE_VEHICULO { get; set; }
        public virtual TIPO_COMBUSTIBLE TIPO_COMBUSTIBLE { get; set; }
        public virtual TIPO_TRANSMISION_VEHICULO TIPO_TRANSMISION_VEHICULO { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPOSITIVO_CLIENTE> DISPOSITIVO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_MANTENIMIENTO> SOLICITUD_MANTENIMIENTO { get; set; }
    }
}
